language: node_js
node_js:
- stable
install:
- npm install
jobs:
  include:
  - stage: test
    name: tests
    script:
    - npm test
    
  - stage: deploy
    script: skip
    before_deploy:
    - npm run build
    deploy:
      provider: heroku
      api_key:
        secure: "frbp/fvgutlxJMrrmLA37lNxrO1atJ56EZgC+wMqZZJFbXYsTOVDtHJcPWeV5jkSt3jSrDGn6YYhlKZ4Me9cFs+4O8nmRcu7FzHy35JqZA3d/ytQUSatA7AUJ8dIe8njZQRkWM+9CgxBzoJ/s/C3ESW4k9dCWdoWype7cK1+UMeYopPROeA4ErpD1CSWBrQx9SIj4XJoEEr3tWYf32Ulgns6a3/WH4FAI6Q1qg4SqABWgIKVnb12cTtrfqtcobZRzNsA31jbPM4G5h3TP4q3y+tAOyR90sm+vm39ES/SFX9IYMVL5TkXZAVeXi2nLfxkXvmOnRNQZoHTICoUUIU3ym+2TaGwjfOU+RaK/5NeMgO8RugEcqu0eF7Yg06ZtuFHnR6+NXgLXOqsOjrgm31WzCE4o1Uye8fKnRvDUiOlC09KRCp4dqq6bKKUqb+ef8mgbhZuz92eAN15D7JDvnR2LNRrWF3XnJJ6oIj8mxvEbaLDkxj1IeAOe9/D0nZzvpRiQ5YvvWyK+SZqJSOWZUccfFxGbcgcRgkNJ+9+cvHBVciroUR0EkeS34ID5OcUMnU2SGvCCWhssGwhpgG5He8a5e8b5rumC22iRYc9sTscd8hoNnXdKq/AW9+Ca83/4rIIntw+2x1dn7RUliMuK/C05M1htXWLi92FqAlh+uszTxY="
