language: node_js
node_js:
- stable
install:
- npm install
jobs:
  include:
  - stage: Tests
    name: Unit Tests
    script:
    - npm test
  - stage: Deploy
    script: skip
    before_deploy:
    - npm run build
    deploy:
      provider: heroku
      api_key:
        secure: NkQ5XrEgD6DnbIX0Cn5N2Wvbt7KOvgkeHORGMnRJ8svfIcN65B6fk0sBaIQvDFWrqQhZa0P/Odre7lmjpKeOnoASKIU4xyCO7qAys9RWWmHgyuK1USJpZIfF/r9MT5LyQFg33VV9l/Gk1EYMnBvpLj9Qm2VuHoQgU060/OOv+IuPPeNY7yMPx7CMe82veTwat+LEvkj1UFks2Hof1ScoEyxrOHnFfQbPq3ihbF79XQsmbOqQQSIrD9BN3ZkNbwtcStwCRbKzXGSthnWaQRRuGoSgI0kHLqnJFQGoymlTYNAbXCy3SdelcsWWmnNPPrqhGTcuD3Ue+1un2p9/zrBSDur12vh4XPCE3B3sr/4UHONR8E2CjCCcqYXR1ucgdgubsA6vK4eQ7hdVbGxhqOOF3bmEHCND0l13yzavz/rr9veO0/dQLigKr7q40WSchA2r+O7VcqQ/mdQQyIAOfKXSpnw1DfmKWz0mk6ihq1YZGt/6WVvxWuZQYer+ZPdrPjzG9QNtPOQRIJOCrd4jm6vfjv7IPCjBrt2BaVlg/pj4s89KzTHJr2YaHlz7g3LEysfedsQ8hDVDLMYsTFivJEeVcYkAxHLipPYiS4fzwke4tkec4oi2kSu/6G0GXQYCY1RKygErhv7Kqze3j/LmsUCpQ3MR+ixleKYIqXAP50SgGt8=
